name = "openpat"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "openpat-db"
database_id = "80d46874-272f-4977-9b85-f0a1c099db88"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "openpat-assets"

[[kv_namespaces]]
binding = "SITE_CONFIG"
id = "f000ffb61a1b4882a4939f59f213b399"
